### ISSUE TITLE
checks failing with runtime error

### ISSUE THREAD

**Issue by VenkataMallareddyNBCU** [elgohr/concourse-sonarqube-notifier#56]
Hi

I've just configured my pipeline with this resource and initial check have been failing with below runtime error. My concourse version is 7.4.0. Could you please provide some insight on this error

```
panic: runtime error: invalid memory address or nil pointer dereference
23:13:35
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6561db]
23:13:35

23:13:35
goroutine 1 [running]:
23:13:35
main.getVersions(0xc0000b60f0, 0x24, 0xc0000b60c0, 0x28, 0xc0000bc090, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
23:13:35
	/concourse-sonarqube-notifier/assets/check/main/check.go:87 +0x2db
23:13:35
main.run(0x723e60, 0xc0000be000, 0x723e80, 0xc0000be008, 0x0, 0x0)
23:13:35
	/concourse-sonarqube-notifier/assets/check/main/check.go:51 +0x18f
23:13:35
main.main()
23:13:35
	/concourse-sonarqube-notifier/assets/check/main/check.go:32 +0x55
23:13:35

```

**Comment by elgohr** [comment]
Thank you for the issue. Will have a look
